dist: xenial 
before_install:
        - sudo apt-get update
        - sudo apt-get install -y pandoc-citeproc
        - sudo apt-get install -y pandoc

language: python
python:
        - "3.7"
install:
        - pip install -r requirements.freeze
        - pip install -e .

script:
        - python bgc_md/tests/run_tests.py
