dist: xenial 
language: python
python:
        - "3.7"
before_install:
        -sudo apt-get update
        -sudo apt-get install -y pandoc 
        -sudo apt-get install -y pandoc-citeproc
install:
        - pip install -r requirements.freeze
        - pip install .

script:
        - python bgc_md/tests/run_tests.py
