# vim:set ff=unix expandtab ts=4 sw=4:
from pathlib import Path
from bgc_md.Model import Model
from bgc_md.autoGeneratedMD_holger import report_from_model

# we could make this a commandline tool that takes one argument
# the yaml_file_name
yaml_file_name="../SoilModels/Zelenev2000MicrobialEcology.yaml"
target_dir_path=Path(yaml_file_name).parent
html_dir_path = target_dir_path.joinpath("html")
model=Model.from_file(yaml_file_name)
dir_name = model.bibtex_entry.key

sub_dir = html_dir_path.joinpath(dir_name).as_posix()
rel = report_from_model(model) 
rel.create_pandoc_dir(sub_dir)

