# general configuration
url: 'https://mpibgc-tee.github.io'
baseurl: '/bgc-md'

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/database.png"
  # author will appear under the avatar (optional)
  author: "BGC-MD"
  # tagline will appear under the title (optional)
  tagline: "The Biogeochemistry Model Database"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  #twitter: "compass"

# exclude
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
