# Generated by Django 2.0.6 on 2018-06-13 18:07

from django.db import migrations, models
import django.db.models.deletion
import yaml_creator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateVector', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FluxDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluxes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FluxRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelDescriptor',
            fields=[
                ('filename', models.CharField(default=yaml_creator.models.default_yaml_file_name, max_length=200, primary_key=True, serialize=False)),
                ('doi', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reverse_execution_order_position', models.IntegerField(default=0)),
                ('model_descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.ModelDescriptor')),
            ],
        ),
        migrations.AddField(
            model_name='componentscheme',
            name='fluxdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.FluxDict'),
        ),
        migrations.AddField(
            model_name='componentscheme',
            name='model_descriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.ModelDescriptor'),
        ),
    ]
