# Generated by Django 2.1.1 on 2018-11-16 20:54

from django.db import migrations, models
import yaml_creator.models.ModelDescriptor


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDescriptor',
            fields=[
                ('folder_name', models.CharField(default=yaml_creator.models.ModelDescriptor.default_model_descriptor_folder_name, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
