# Generated by Django 2.0.5 on 2018-05-31 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pup_date',
            new_name='pub_date',
        ),
    ]
