# Generated by Django 2.0.6 on 2018-07-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statevariable',
            name='componentscheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.StateVector'),
        ),
    ]
