# Generated by Django 2.0.6 on 2018-07-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldescriptor',
            name='doi',
            field=models.URLField(),
        ),
    ]
