# Generated by Django 2.0.6 on 2018-06-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donating', to='yaml_creator.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='InFlux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(max_length=200)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to='yaml_creator.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='OutFlux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(max_length=200)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donating', to='yaml_creator.Variable')),
            ],
        ),
        migrations.RenameModel(
            old_name='SingleFlux',
            new_name='InternalFlux',
        ),
    ]
