# Generated by Django 2.0.6 on 2018-06-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxes',
            old_name='componentScheme',
            new_name='componentscheme',
        ),
        migrations.RenameField(
            model_name='matrices',
            old_name='componentScheme',
            new_name='componentscheme',
        ),
    ]
