# Generated by Django 2.0.5 on 2018-06-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateVector', models.CharField(max_length=200)),
                ('reverse_execution_order_position', models.IntegerField(default=0)),
                ('model_descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.ModelDescriptor')),
            ],
        ),
        migrations.CreateModel(
            name='OutputAndTransitFluxRepresentations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompartmentalMatrix',
            fields=[
                ('outputandtransitfluxrepresentations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yaml_creator.OutputAndTransitFluxRepresentations')),
            ],
            bases=('yaml_creator.outputandtransitfluxrepresentations',),
        ),
        migrations.CreateModel(
            name='Fluxes',
            fields=[
                ('outputandtransitfluxrepresentations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yaml_creator.OutputAndTransitFluxRepresentations')),
            ],
            bases=('yaml_creator.outputandtransitfluxrepresentations',),
        ),
        migrations.AddField(
            model_name='outputandtransitfluxrepresentations',
            name='ComponentScheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.ComponentScheme'),
        ),
    ]
