# Generated by Django 2.0.6 on 2018-06-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0002_auto_20180622_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalflux',
            old_name='fluxrepresentation',
            new_name='fluxes',
        ),
    ]
