# Generated by Django 2.0.6 on 2018-06-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0002_auto_20180621_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.Variable'),
        ),
        migrations.AlterField(
            model_name='influx',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.Variable'),
        ),
        migrations.AlterField(
            model_name='outflux',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.Variable'),
        ),
    ]
