# Generated by Django 2.0.6 on 2018-07-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0002_auto_20180710_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldescriptor',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
