# Generated by Django 2.0.6 on 2018-06-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0002_singleflux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleflux',
            old_name='doi',
            new_name='expr',
        ),
        migrations.RemoveField(
            model_name='singleflux',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='singleflux',
            name='source',
            field=models.ManyToManyField(related_name='SourcePool', to='yaml_creator.Variable'),
        ),
        migrations.AddField(
            model_name='singleflux',
            name='target',
            field=models.ManyToManyField(related_name='TargetPool', to='yaml_creator.Variable'),
        ),
    ]
