# Generated by Django 2.0.6 on 2018-06-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0003_auto_20180619_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleflux',
            name='source',
        ),
        migrations.AddField(
            model_name='singleflux',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='donates', to='yaml_creator.Variable'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='singleflux',
            name='target',
        ),
        migrations.AddField(
            model_name='singleflux',
            name='target',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='receives', to='yaml_creator.Variable'),
            preserve_default=False,
        ),
    ]
