# Generated by Django 2.0.5 on 2018-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0003_auto_20180611_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='pos',
            new_name='reverse_execution_order_position',
        ),
        migrations.AddField(
            model_name='modeldescriptor',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
