# Generated by Django 2.0.6 on 2018-06-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0003_auto_20180622_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalflux',
            name='fluxes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_creator.Fluxes'),
        ),
    ]
