# Generated by Django 2.0.6 on 2018-07-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0003_auto_20180713_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.CharField(default='enter your description here', max_length=200),
            preserve_default=False,
        ),
    ]
