# Generated by Django 2.0.6 on 2018-06-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0003_auto_20180621_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxsource',
            name='source',
        ),
        migrations.DeleteModel(
            name='FluxSource',
        ),
    ]
