# Generated by Django 2.0.5 on 2018-06-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_creator', '0004_auto_20180611_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='name',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
    ]
