def template(model):
    rel=ReportElementList()
    sdp= defaults()["paths"]["report_templates"].joinpath("single_model")
    
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="additional_variables")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="photosynthetic_parameters")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="photosynthesis_and_respiration")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="water_availability")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="nutrient_uptake")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="respiration_fluxes")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="respiration_parameters")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="respiration")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="partitioning")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="allocation_fractions")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="allocation_coefficients")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="allocation_fluxes")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="partitioning_rates")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="partitioning_parameters")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="partitioning_coefficients")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="cycling_rates")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="transit_parameters")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="temperature")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="phenology_parameters")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="litter_fluxes")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="release_rates")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="turnover_fluxes")
    rel += render(sdp.joinpath("vSectionVariablesTable.py"),model,section="litter")
    return rel

